version: "3.8"
services:
  mongodb:
    image: "mongo"
    restart: always
    volumes:
      - data:/data/db

  nginx:
    image: clab-manager:proxy
    restart: always
    ports:
      - "5000:80"

    depends_on:
      - frontend
      - backend
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./app/node_modules

    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true

    depends_on:
      - backend

volumes:
  data: